paper_base=[
    {
        "name": "马榕.基于轴辐式网络的区域港口群多式联运网络优化研究[D].导师：王喜富.北京交通大学,2022.",
        "abstract": "在全球经济一体化和港口腹地融合发展的大趋势下,同一经济地域范围内的不同港口由于共同腹地、共同利益而联结到一起,形成了区域港口群。区域港口群与经济腹地所构成的多式联运系统也逐渐复杂化,为提升多式联运网络运行效率,需要采取科学的方法对其进行优化。为此,本文首先采用烟羽模型对港口群交叉腹地进行了划分,并在此基础上构建了基于轴辐式网络的多式联运网络双层规划模型,通过求解模型寻找网络优化的最佳方案。本文首先系统地介绍了港口腹地划分问题及多式联运网络优化问题的研究现状,并概述了区域港口群多式联运网络优化问题的相关理论基础。之后,梳理了港口腹地划分的一般方法,在分析各类划分方法的优势与不足的基础上,构建了区域港口群交叉腹地划分的烟羽模型,并明确模型中关键变量的求解思路和具体方法。之后,在确定各港口所属腹地的基础上,构建单枢纽混合轴辐式结构下的多式联运网络,以多式联运经营人总成本最小以及单个港口经营人利益最大为目标,建立多式联运网络双层优化模型,对模型的组成要素进行详细分析,依据“线性规划+遗传算法”的思路对模型进行求解。最后,以山东沿海港口群为研究对象,利用SPSS、MATLAB等软件对腹地划分的烟羽模型和多式联运网络优化模型进行求解,求解结果具有一定实际意义,有效地验证了模型的可靠性,为多式联运网络运输组织计划安排提供参考。论文图32幅,表42个,参考文献67篇。"
    },
    {
        "name": "陈旭,张向阳,孙之翼,陆丽丽.江海联运网络优化——以宁波舟山港为例[J].物流技术,2022,41(04):22-31.",
        "abstract": "为高效准确地找出某地江海联运可发展运输网络,提出了江海联运网络优化模型。首先模拟江海联运应用的现实条件和运作方案,构建江海直达、江海中转和江海直驳三种江海联运模式的成本模型;其次建立效用选择模型,计算和比较某港与其竞争对手的费用、时间、安全和稳定的综合效用;最后建立网络优化模型筛选出可行的江海联运需求路线。以宁波舟山港为例,结合厦门港至武汉港的杂货运输案例进行仿真分析,证明宁波舟山港可作为江海联运中转主选择港,并进一步得到所有宁波舟山港可被选择的江海联运线路,集成为宁波舟山港江海联运网络优化表。"
    },
    {
        "name": "肖月.长江至金塘港区江海联运发展对策研究[D].导师：王家宏.浙江海洋大学,2017.",
        "abstract": "在《全国海洋经济发展“十二五”规划》、《浙江舟山群岛新区发展规划》、《舟山江海联运服务中心总体方案》等国家战略为舟山金塘港构建江海联运航运服务体系提供了良好契机的战略环境下,本文研究了舟山金塘港发展江海联运的可行性、必要性以及存在的问题,并在借鉴其他江海联运发达港口经验的基础上,提出了金塘港发展江海联运的对策。本文的研究结果表明:1.从重庆港出发到舟山金塘港的航线,从太仓港中转要比重庆港直达舟山金塘港的运输模式必要运费率更低,此时我们选择中转的运输方式;2.从武汉出发到舟山金塘港的航线,江海联运的必要运费率比从其它港口中转的必要运费率更低,此时选择江海联运的运输模式会更具经济性;3.从南京出发到舟山金塘港,江海联运的必要运费率比从太仓港中转的必要运费率更低,选择江海联运的运输方式会更具有经济性;4.提出了长江不同港口到舟山金塘港最优船型和最优路线,并对这些影响因素进行优化建议。本论文研究成果的可供航运公司选择船型时作参考,也可为舟山金塘港以及沿江各省市的决策者为航运业的发展提供决策支持。"
    },
    {
        "name": "衡强.长江至洋山港区江海联运发展战略模式研究[D].导师：史安娜.河海大学,2007.",
        "abstract": "加快长江到洋山深水港区的集装箱运输发展是贯彻落实中央提出的建设上海国际航运中心为龙头，带动沿江经济发展战略部署的重要举措。洋山深水港区的建设和投入使用将对整个长江集装箱江海联运的运输体系发生革命性的变化，洋山港区与长江干线组成了集货源、航道、港口及船舶为一体的国际集装箱运输的大系统，本文以战略管理理论为指导，通过可行性分析、SWOT分析及成本最小模型对未来长江到洋山港区的江海联运方式做战略规划与优化，以实现港口布局与航线设置的最佳组合，探索长江到洋山港区江海联运的最优战略发展模式。 本文主要分为三大部分，第一部分主要分析长江集装箱运输的历史沿袭及洋山深水港区建设对长江现有集装箱运输模式的影响进行了评估。其次主要对未来长江内“二次中转”的开展进行了分析和讨论并对具备开展“二次中转”条件的港口进行了初步的筛选与比较。最后采用了成本最小化模型，对长江到洋山中转箱的换装运输模式进行了比较，并就湘、赣江里一类危险品运输的特殊性进行了探讨。最后对于长江到洋山深水港区的运输模式的发展战略提出措施与建议。"
    },
    {
        "name": "游甜.舟山江海联运运输网络成本优化研究[D].导师：沈最意.浙江海洋大学,2017.",
        "abstract": "舟山地处长江三角洲经济腹地,经济发展环境优越,加之上海航运业发展带来的积极影响,舟山航运业发展迅速。结合自身地理区位优势和优良的深水港、深水航道优势,舟山江海联运建设前景一片光明。本文对舟山江海联运体系及其运输网络进行了介绍和研究,研究的重点是控制舟山江海联运网络运输成本,在低运输成本的基础上,选择运输路径、中转运输港口和船舶吨级。首先,本文对舟山的自然条件、地理区位、航道条件、港口条件和航运业的发展现状进行了详细的说明。其次,本文介绍了舟山江海联运运输流程的三个阶段,分别是陆路运输、内河航运、海上运输。在此基础上,讨论了舟山江海联运运输网络的四个主要影响因素,它们分别是货物需求、航道情况、港口建设和船型选择。并对这四个主要影响因素之间存在的相互关系、作用和影响进行了分析总结。在明确舟山江海联运运输的四个主要影响因素等问题的情况下,为进一步优化舟山江海联运网络,本文引入了虚拟港口的概念、设置了约束条件和参数、确定了目标函数,进行了最低运输成本下的建模分析,最后通过实例进行了进一步的分析说明,得到了运输总成本最低情况下的舟山江海联运的运输路径,确立了货物接收港和中转港,合理选择了船舶吨级。但是由于数据的收集却无法做到完全的精确、参数的近似选取以及作者学术水平的有限性,此研究结果仅做参考之用。"
    },
    {
        "name": "孔吴琼.长江水系散货江海联运运输网络优化布局研究[D].导师：肖汉斌.武汉理工大学,2014.",
        "abstract": "本文首先是从长江水系水运运输系统着手来分别分析长江水系地理环境、沿江港口概况、航道建设现状、各主要港口发展现状以及长江水系散货运输组织方式，了解到长江水系有良好的地理区位、发达的航运网络、较好的航道条件以及优越的自然条件。但是同时长江水系还存在某些航段的航运能力受到航道条件的限制、三峡船闸通航能力较低、干线中游有较多的浅滩等不良情况，这些问题都会影响长江水系散货江海联运的发展，所以急需国家和沿江各省市采取一些有力措施解决这些问题。其次，本文又介绍了长江水系散货江海联运运输流程的三个步骤并展示了运输流程图。通过对长江水系散货江海联运各方面的描述和分析，并且为了达到优化运输网络布局的目的，本文虚设了一级港口群并设置了一些假设条件，然后综合考虑船舶吨级、航道条件、港口建设、货物供应量、货物需求量等约束条件，最终建立了以运输总成本最小为目标的模型。将实例应用于模型并进行运算，得到了运输总成本最低情况下的长江水系散货江海联运的运输路径选择、散货接收港和中转港的选择、运输船舶吨级的选择以及每条路径上的年货运量等相关参数，从而为长江水系散货江海联运的发展提供一些建设性的意见。"
    },
    {
        "name": "张懿慧.珠江水系集装箱江海联运运输网络优化研究[D].导师：曾敏刚;雍清赠.华南理工大学,2017.",
        "abstract": "本文在对珠江水系集装箱江海联运的现状和模式分析的基础上,对江海联运运输网络进行了研究,并提出相关建议。针对珠江水系江海联运货物起始地覆盖广阔、分散分布,货物目的地相对集中的具体情况,研究集装箱运输过程中多级联运模式的特点,建立起包括集装箱起始地、内河支线港、沿海中转港在内的运输网络,通过分析网络目标函数和约束条件研究不同条件下的运营成本,确定珠江水系集装箱江海联运的成本最优选择。本文首先介绍了珠江水系的自然条件,现有港口和航道情况以及现有的水运网络和联运体系。总结出珠江水系优良的天然条件和丰富资源,水陆联运系统初具规模等现状,但同时集运系统航线运输不发达,港口分布不均衡,船型匹配不合理等问题,亟待通过江海联运网络的建设来解决。在掌握珠江水系概况的基础上,调研现有珠江水系集装箱江海联运的发展模式、运营主体、存在问题,从珠江水路运输需求,航道通航情况,码头的建设及船型选择等四个方面展开,在对此分析的基础上建立了珠江水系集装箱江海联运运输网络成本最优选择模型,对不同选择下的水路运输成本进行测算,进行优化选择,并从货运需求、港口费用、船队运力供给、港口利益主体等四个方面进行了定性的敏感性分析。最后,综合研究结论,同时适当借鉴国内外江海联运发展的经验做法,为内河支线港和沿海中转港发展江海联运提出建议,总结并提出珠江水系集装箱江海联运发展的思路和对策。"
    },
    {
        "name": "张雷.南通市江海河联运设施布局方案研究[J].港口经济,2016,(12):44-45.",
        "abstract": "南通市处于沿海经济带与长江经济带T型结构交汇点,具备发展江海河联运的先天区位优势。本文针对江海河联运的概念和构成,结合南通江海河联运的实际状况,提出未来南通市江海河联运节点、联运通道、运输系统等提升的路径及保障措施,以推动南通市江海河联运的跨越式发展,更好地服务沿江沿海港口建设和临港产业的发展。"
    },
    {
        "name": "陈昊奇.长三角区域集装箱多式联运网络一体化构建与空间结构分析[D].导师：王育红;孙崇波.宁波大学,2021.",
        "abstract": "长三角地区在中国经济增长和国际贸易发展中占有重要地位,外贸进、出口总额占全国比重超过30%,集装箱进出口运输需求持续增长。然而长三角现运输网络存在各运输方式发展失衡,各基础设施之间互联互通程度低,传统运输通道布局单一等问题,无法满足现长三角地区日益增长的高质高效运输要求。因此,打造一体化多式联运网络是提供高质量、便捷灵活的多式联运服务和提升运输网络竞争力的关键。同时,一体化的综合交通运输体系也是十四五建设明确优先发展的促进国民经济发展的先导性、基础性产业。一体化多式联运网络建设是实现长三角地区运输资源合理配置,充分发挥区域产业基础优势和物流枢纽聚集优势的有效依托。本文拟通过复杂网络空间结构分析方法对长三角各节点城市在运输网络中的地位和作用进行量化解读,准确识别关键节点和主要运输通道,为长三角地区综合交通运输体系建设提供理论支撑。本文首先介绍了长三角地区集装箱多式联运网络的组成和发展状况,然后研究了建立基于跨运输方式组合的集装箱运输网络模型构建方法。本研究中的一体化集装箱多式联运网络以长三角区域内的一市三省34个城市为基本节点,任意节点对之间的公、铁、水运输服务为连线。同时,基于区域内集装箱货物流特征,引入德国汉堡、美国洛杉矶、马来西亚巴生作为外部节点分别代表欧洲、美国和东南亚市场的进出口货物流起讫点。通过利用运输成本、时间成本以及基于运输方式转换带来的惩罚成本等构建的阻抗函数建立交通流分配模型,对各节点对之间的路径进行配流,实现代表不同运输方式三层运输网络的多网融合的拓扑表达。其次,在一体化运输网络的基础上,本研究使用复杂网络空间结构分析方法对该网络的性能,如网络密度、平均路径长度、平均度、度分布、聚类系数等指标进行测量,探求运输网络的性能表现、类型和发展方向,同时对节点性能指标(中心度)进行分析,测量各节点城市的结构中心度、通达性和可达性等指标,为探讨各运输节点城市在长三角运输网络中的地位、作用和发展方向提供参考。研究结果表明现阶段长三角多式联运网络为规则网络形态,存在运行效率欠佳且稳定性不高的缺陷,其原因是该网络平均路径长度高于同规模运输网络,且度分布不符合幂率分布。其次,集装箱水运网络建设对未来长三角多式联运网络格局影响至关重要,安徽地区的长江干线以及长江沿岸港口城市的江海联运服务将极大影响各节点城市的通达性和枢纽地位。此外,现长三角区域内的国际性综合交通枢纽发展进程滞后,南京、杭州的内河运输体系仍有较大提升空间;上海、苏州在网络中承担门户枢纽的功能,芜湖、宁波、南京在网络中承担长三角的中转枢纽功能;本研究除验证政府规划的运输通道的和合理性同时,新提出长三角多式联运网络的北侧运输通道和西侧运输通道,以用于货物的流通和中转。"
    },
    {
        "name": "A Multi-objective Optimization Model of the Intermodal Transportation Network[A].in:American Society of Civil Engineers.International conference on transportation engineering 2009, vol. 2: Second international conference on transportation engineering (ICTE 2009), July 25-27, 2009, Chengdu, China[C].2009.1244-1249.",
        "abstract": "Nowadays the optimization of the intermodal transportation network is an interesting topic on which attracts many people to do research. Consideration the characteristic of the intermodal transportation network, this paper present a multi-objective optimization model under the principle of the minimization of the transportation cost and time. The model quantificationally describes the combined optimization strategy for every transportation modes in the intermodal transportation network. And then the author proposes the solution methods for the multi-objective optimization model based on the Matlab Toolbox. At last, this method is used to settle a simple example which is composed of several cities and four transportation modes. The results indicate that this methodology is effective to find the combined optimization strategy for transporting. And the research enables to help the transportation enterprise (and other organization) select the transportation modes, combined strategy and route."
    },
    {
        "name": "Intermodal transportation in Istanbul via Marmaray[J].IBM journal of research and development,2010,54(6):1-10.",
        "abstract": "Intermodal transportation (IMT) combines two or more different modes of transportation without changing the packaging of the freight transported in order to minimize the transportation cost and to utilize the benefits of modes that are used. One of the most common intermodal freight transportation systems is the Rolling Highway (Ro-La), where a special train system is used to carry highway vehicles on railway cars. This paper reviews IMT and proposes a system in which the facility layout problems are solved simultaneously with the scheduling problems arising in Ro-La transportation. In this context, the best station layouts are obtained by applying a layout improvement algorithm to several initial layouts with respect to different scoring functions. One of the important questions to answer in the IMT problem pertains to the number of loading and unloading platforms. Using the output of the layout improvement algorithm, the train scheduling model is solved to find the minimum number of platforms in a station, the number of trains, and the departures with the carried trucks and trailers, while scheduling train operations, with the objective of minimizing operation costs. The proposed IMT system is applied to the Marmaray Undersea Railway Tunnel Project with regard to different Ro-La systems, and its effectiveness is discussed."
    },
    {
        "name": "赵怡然.长江经济带沿线出口集装箱的运输组织优化研究[D].导师：赵旭.大连海事大学,2021.",
        "abstract": "江海直达、中欧班列等新运输服务提高了长江经济带地区出口集装箱的运输能力、运营效率和服务质量,在新的形式下承运人(包括货代)可以实施更高效细分的运输组织。因此,有必要评估长江经济带区域内贸易运输便利性的改善程度,分析预测新诱增的出口集装箱的运输量,明确其对出口运输组织的需求。针对长江经济带地区中欧班列发班城市出口到欧洲的集装箱,细分运输市场,研究海运班轮与铁路班列的协同运输问题,优化班列与班轮的运输组织方案。同时,为依托长江黄金水道及其周边的其他运输方式实施江-海-陆协同的出口集装箱运输,多元化组合长江经济带的陆路、水路、近洋航路与远洋航路的运输资源,有必要区分江海直达和江海联运,优化长江经济带出口到近洋海外的集装箱的运输方案和运输系统。为此,本文拟开展的研究内容如下所述:(1)根据可达性的物理内涵,定义空间单元的效用可达性指标、机会可达性指标,基于两种可达性指标的定义,提出计算空间单元的外贸运输可达性的方法。基于外贸运输可达性指标,分析长江经济带地区中欧班列发班城市(这里以重庆市为例)对外贸易运输的便利性和连通性的发展态势;基于生产与消费的关系,利用随机前沿分析法和多因素动态生成法,提出计量发班城市出口到欧洲的集装箱需求的的变化情况。把国际贸易运输水平、产业多样化、中欧班列的贡献率3个指标作为评价发班城市物流中心的要素,研究中欧班列对其发班城市国际物流需求的影响以及对欧出口集装箱运输组织的需求变化。(2)收集与分析中欧之间各种贸易运输方式的市场份额数据,构建集装箱贸易运输方式分担模型。把集装箱运输的时间划分为在途时间、装卸时间和等待时间;把运输费用分解为运输过程费用、运输期间的库存费用、运输期间货物占用资金的机会成本和随时间的贬值成本。基于历史数据和方式分担率模型,分货类标定9类中欧之间贸易商品的时间价值。基于敏感性分析,研究货物时间价值及中欧班列发班频率与运价对3种运输方式在9类商品的集装箱运输市场上的份额的影响,针对细分中欧之间的集装箱运输,细分3种运输方式(即中欧班列、航空货运和集装箱班轮航线)的市场,提出海铁协同的中欧间贸易集装箱运输的组织方案。(3)根据长江经济带地区的海运、水运、铁路运输和公路运输通道,构建超级运输网络,提出把多种运输方式的通道能力和服务水平转化为相应的路段阻抗函数的方法。把货物的时间价值集成到超级网络上各路段的阻抗函数中,基于城市到海外港口的集装箱运输需求,利用用户均衡交通分配模型为集装箱货物指派走行路径,以运输成本最小为目标,优化枢纽河港与近洋海外目的地港之间的江海直达班轮航线、班轮船舶数量以及班轮发班频率。根据网络中节点通过的集装箱流量多少确定长江经济带域内的内陆干港、枢纽河港和门户海港的选址。为在多模式联运的国际贸易网络中计算各种路段的运输阻抗和多模式枢纽节点选址提供新的技术方法,为江海直达班轮运输组织奠定理论基础。"
    },
    {
        "name": "张文瀛.内河集装箱多式联运系统优化及协同策略研究[D].导师：王喜富.北京交通大学,2020.",
        "abstract": "随着“一带一路”、“交通强国”等国家战略的提出,“公转水”、“公转铁”和“散改集”等政策的推行,我国交通运输行业越发重视发展多式联运,强化集装箱运输的系统化应用,这一趋势为集装箱和多式联运的发展提供了良好的产业政策和市场环境,也促使内河集装箱铁水联运业务蓬勃发展。研究内河集装箱多式联运系统优化和协同策略,不仅可以推动内河综合运输业务自身的变革,推进内河多式联运组织的优化与标准的建立,还可以实现内河运输与陆路运输、内河与海运等多种运输方式的协同合作,实现集装箱在联运网络上的高效移动与系统优化。本文综合运用系统工程理论与方法、不确定规划方法、排队论、博弈论等基础理论,通过定性分析与定量计算相结合的方式,研究了内河集装箱多式联运的网络优化、货流分配、运输方案优化及组织协同四个方面的问题。(1)界定内河集装箱多式联运系统。提出了内河集装箱多式联运系统内涵,并将其表达为“内河内部干线转运”和“内河外部支线分流”两个层面的系统构成,同时将轴辐式网络与其结合,给出了内河集装箱轴辐式多式联运网络框架,基于网络的边和节点的拓扑结构抽象原则,构建了多模式分层次立体化的拓扑结构模型。(2)研究整个内河集装箱联运系统的网络优化问题。利用不确定分布方法刻画了联运网络的多维不确定性,构建了基于不确定规划的双目标优化模型,推导出了期望值目标函数和机会约束的确定性等价形式;再结合Epsilon约束方法和文化基因算法,设计了混合智能算法;然后通过长江干线联运网络实例和TR网络数据对模型和算法进行了验证,结合灵敏度分析,探讨了集装化系数和转运节点数量对最优时间和成本目标值的影响,结果表明集装化系数越小,集装化程度越高,单位运输时间所需要的运输成本越低,因此提高内河多式联运的集装化程度,有助于联运系统的降本增效。(3)研究集装箱在内河外部集疏过程中所形成的支线分流网络的货流分配问题。通过综合考虑分流枢纽、内河枢纽节点和运输通道的三重容量限制,利用minmax决策准则构建了混合整数非线性规划模型,再引入线性化技术将原模型转化为线性规划模型;并在分枝定界法的基础上采用切割平面方法,设计了分枝切割法进行求解;接着,以长江沿线集装箱集运分流网络为算例进行研究,通过灵敏度分析,探讨了不同容量限制对最优目标值和货流分配网络演化过程的影响,结果表明随着水路直运通道容量值的增加,内河在货流分配方案中承担的运输量越多,越能大幅度降低总运输费用,因此提高内河的通行能力,有助于实现集装箱多式联运供求总量均衡、联运网络货源配置最优。(4)研究集装箱在内河干线运输过程中所产生的过闸拥堵、船舶通过时间长、运输效率低等运输方案优化问题。应用M/M/c排队论,描述了船舶在内河的过闸排队过程,采用两阶段建模思想分别建立了双目标路径优化模型和运输模式选择模型;并针对路径优化模型,利用改进的分枝定界算法进行求解,针对模式选择模型,利用时间成本对比分析法,进而得到优化的联运方案;再以长江干线的三峡枢纽港作为案例,结合灵敏度分析,探讨了排队等待时间对联运方案的影响,结果表明在内河干线运输过程中,可以通过多运输模式的选择降低船舶等待时间;最后,对翻坝联运、水水过驳模式与传统水运做了相关指标对比分析,结果表明这两种模式均能够减少船舶待闸时间,因此通过提高升船机数量及载运量,加强翻坝公路、铁路通道的建设,有助于提高内河干线转运效率。(5)研究非对称信息下的内河集装箱多式联运组织协同策略问题。围绕内河集装箱多式联运经营人和各承运人之间的协同关系,构建了基于期望和熵决策准则的不确定双层规划模型;再针对信息对称和信息不对称两种情况,设计了两步优化算法,以此分别获得了最优激励合同的清晰表达式;结合算例分析,探讨了非对称信息对内河集装箱多式联运合同设计和收益分配的影响,结果表明激励系数随风险规避水平增加而降低,信息价值随风险规避水平增加而增加,多式联运经营人(MTO)获取信息的意愿也随风险规避水平增加而变得强烈。因此,在非对称信息条件下,MTO作为联运服务集成商及联运方案决策者,通过引入最优合同机制,对组织整体收益进行合理分配,是优化内河多式联运组织协同的较佳策略。"
    },
    {
        "name": "陈红.港口-腹地集装箱多式联运网络弹性的提升研究[D].导师：刘南.浙江大学,2018.",
        "abstract": "集装箱运输与集装箱港口行业的发展是国际贸易繁荣的重要保障。在国际集装箱运输链中,陆上部分的港口-腹地集装箱运输占据了总成本的一半以上,保证港口-腹地集装箱运输系统的运作效率是国际集装箱高效运输的关键。另外,考虑到多式联运在运输成本、运作效率和环境保护方面的独特优势,本文着重对港口-腹地集装箱多式联运网络弹性的提升问题进行系统研究,以期保证该网络足够稳健和灵活,能够有效抵抗各种非常规突发事件的威胁和冲击,具有切实的现实意义和重要的理论创新价值。具体而言,本文的主要内容包括:(1)港口-腹地集装箱多式联运网络弹性的事前预防提升研究。聚焦于非常规人为突发事件的事前阶段,从集装箱运输服务提供商的角度,考虑不同参与方间复杂的商业关系,基于网络博弈理论构建数学模型,在战略层面研究个体参与方的事前预防投资决策对网络整体弹性水平提升的作用影响。然后,通过实地走访调研宁波舟山港集团,将理论模型得出的纳什均衡解的理论分析结果与宁波舟山港案例研究的数值仿真实验结果相结合,为事前预防阶段的网络弹性提升问题提供管理启示与政策建议。(2)港口-腹地集装箱多式联运网络弹性的事后恢复提升研究。聚焦于非常规突发事件的事后阶段,从集装箱货主的角度构建两阶段整数规划模型,在运营层面研究即时恢复措施对网络弹性水平提升的作用影响。然后,将构建的理论模型应用于瑞典哥德堡港及其腹地的公铁联运网络中,通过实地调研和数值仿真实验,对该案例网络在三种非常规突发事件情境下的弹性水平进行定量测度与比较,分析不同事后即时恢复措施对网络弹性水平提升的作用影响,为事后恢复阶段的网络弹性提升问题提供管理启示与政策建议。(3)港口-腹地集装箱公水联运网络弹性全面评价与优化研究。从弹性概念出发,在文献研究的基础上,基于多位学术界和业界资深专家的专业意见,构建港口-腹地集装箱公水联运网络应对非常规自然突发事件的弹性评价体系。该评价体系旨在对网络弹性进行全面而系统地综合评估,包括在事前预防和事后恢复阶段、战略层面和运营层面上的弹性建设能力,以定量和定性研究方法相结合的实证研究对那些无法在数学理论模型中被研究的、但又对网络弹性能力有着重要影响的因素做进一步深化研究与讨论。然后,将此弹性评价体系应用于我国长江和珠江水系的港口-腹地集装箱公水联运网络具体案例中,通过收集相关一手数据和二手数据,利用基于证据推理法改进的层次分析法对这两个案例网络的弹性进行比较评价。评价结果可用于定位这两个案例网络中的弹性弱点,为其弹性的提升与全面优化提供政策建议与管理启示。本文的重要理论创新和实践贡献包括:研究问题方面,本文将弹性概念应用于交通运输领域中,聚焦于港口-腹地集装箱公铁联运网络和公水联运网络在非常规人为和自然突发事件下的弹性问题研究,既丰富了港口-腹地集装箱运输系统的研究,也拓展了弹性概念的应用范围,填补了该领域的研究空白。研究思路方面,本文以“先分开再综合”的思路,对非常规突发事件下港口-腹地集装箱多式联运网络弹性的提升问题进行了系统研究,先分别在事前阶段的战略层面基于预防措施、在事后阶段的运营层面基于即时恢复措施,对网络弹性的提升问题进行讨论,然后再基于网络弹性的综合评价结果对网络弹性的系统优化进行详细分析。研究方法方面,本文综合运用多种研究方法,包括创造性地使用网络博弈理论研究网络参与方间复杂的商业关系对网络弹性提升的影响、创造性地从货主角度构建整数规划模型研究即时恢复措施对网络弹性提升的作用、以及创造性地提出基于证据推理法改进的层次分析法对网络弹性进行全面评价与优化研究等,将理论与实证研究相结合、将定量与定性研究相结合。实践贡献方面,本文的研究成果有助于港口企业、航运企业、腹地公路和铁路运输商、以及相关政府部门认识到弹性概念在港口-腹地集装箱多式联运网络应对非常规突发事件时的重要性,为该网络的弹性建设与提升提供切实可行的管理启示和政策建议。"
    },
    {
        "name": "张欢欢.集装箱顶推船队甩挂水水联运运作模式及运输组织研究[D].导师：肖汉斌.武汉理工大学,2014.",
        "abstract": "本文将可以减少装卸环节从而提高运输效率的甩挂运输用于集装箱内河运输，采用可以灵活编组的集装箱顶推船队提高水路运输的灵活性，并且试图通过港口及航运等企业的联合整合资源，提高资源利用率，降低运输成本，设计了集装箱顶推船队甩挂水水联运这一新型运输方式，整合集装箱顶推船队运输、甩挂运输和水水联运的优势，应对激烈的竞争，并改善长江集装箱运量增长和运力不足的矛盾，缓解公路和铁路运输压力。论文首先概述了集装箱顶推船队、甩挂运输和水水联运相关研究和应用，并对长江内河航运进行了分析，得出集装箱顶推船队甩挂水水联运这一新型模式具有理论研究价值和实践指导价值。然后论文从集装箱顶推船队甩挂水水联运的特点、长江水道运输环境两个方面分析该模式的适用性；在分析总结长江现有的各种运输模式的基础上，设计了集装箱顶推船队甩挂水水联运“两点服务”、“循环服务”、“网络服务”三种运作模式和“股权联合”、“框架协议”、“虚拟协同”三种合作模式，并分析了其功能和作业流程。接着论文对该模式的货源组织问题、相关衔接问题、驳船调运问题和风险问题进行了分析和研究，并对集装箱顶推船队甩挂水水联运运输组织建立了数学模型，通过启发式算法对实例模型进行求解，给出了集装箱顶推船队甩挂水水联运的运输方案。本文通过对比传统运输方案和集装箱顶推船队甩挂水水联运运输方案的成本，得出本文提出的运输模式可以有效地减少船舶需求数量，减少集装箱装卸环节和船舶靠泊次数，从而有效提高运输效率，降低运输成本。"
    },
    {
        "name": "尹传忠,邱慧妍,柯媛定,刘咪,武中凯.区域主枢纽港多式联运网络协同优化[J].铁道科学与工程学报,2022,19(01):63-70.",
        "abstract": "综合运输体系是区域一体化的重要组成部分，而多式联运作为综合运输体系一种先进的运输组织模式是区域一体化的桥梁和纽带。为实现集疏运结构合理化，运输网络协同化，解决区域主枢纽港定位不明确、同质化竞争、运输资源浪费等问题，以最小碳排放及运输成本为目标，以运输时间、线路能力等为约束条件，构建由起点、中转点、终点及3种运输方式构成的主枢纽港多式联运网络协同优化模型。设立虚拟中转点以简化网络计算复杂度，利用理想点法将双目标转化为单目标模型进行求解。以长三角地区为例，构建以上海港和宁波舟山港为主枢纽港的多式联运网络，计算得到两大枢纽港的区域内腹地划分、运输路径及运输方式的选择优化结果。研究结果表明：用理想点法将双目标转化为单目标模型进行求解，相比于主观设置权重、多组解集的帕累托解，理想点法更加简明直观。在长三角区域的主要城市中，阜阳、蚌埠、芜湖、马鞍山、安庆、滁州、徐州、苏州、无锡等城市最终划分为上海港腹地，衢州、台州、温州、金华、嘉兴、绍兴等城市作为宁波舟山港腹地。随着约束时间的增加，铁路运输和水路运输逐渐代替了公路运输，而在长三角区域水路运输增加，会导致碳排放成本增加。因此在实际情况中，应当增加铁路运输、鼓励船舶使用清洁能源。研究成果可为区域一体化背景下的多式联运协同发展提供决策支持。"
    },
    {
        "name": "卢文昌.长江中游区域集装箱运输组织优化研究[D].导师：张培林.武汉理工大学,2020.",
        "abstract": "在国家大力发展绿色循环经济、建设交通强国、实施“长江经济带”战略和“一带一路”倡议等一系列背景下,具有运量大、成本低、排放少等众多优势的内河水运迎来了新的发展契机。而集装箱是内河水运的主要运输货种之一,近年来持续快速增长,多式联运也在不断发展中。近几年,交通部大力推动集装箱多式联运,江海直达、铁水联运等取得阶段性成果。由于长江中游航道的重要性,集装箱需求巨大,现有运输组织方式无法发挥其规模效应,因而就中游区域制定出科学合理、成本低廉的集装箱运输组织方案具有十分重要的意义。为此,本文展开相关研究工作,主要如下:首先,以长江中游区域集装箱运输组织为基础,重点分析了航线、运输工具、运输组织条件和运输费用等,并指出了存在的问题;其次,阐述了集装箱运输需求预测思路和方法,基于四阶段法,分别从交通生成和交通分布两个环节预测出了2020-2030年长江中游集装箱运输OD需求量;再次,将交通分担和交通分配两个阶段融合,根据系统性、高效性和经济性的原则,以现有运输组织为基础设计2020-2030年长江中游区域集装箱运输组织方案,并分三个阶段构建规划模型,依次在运输路径优化阶段构建双目标规划模型,运输方式优化阶段构建0-1规划模型,运输工具优化阶段构建单目标规划模型;最后,通过分析比选不同优化算法,选取了自适应蚁群算法和禁忌搜索算法的混合优化算法,设计了适合求解多阶段规划模型的优化算法,最终得出了2020-2030年长江中游区域各线路的最优集装箱运输组织方案。论文的研究提供了一套集运量预测、运输组织方案设计、优化模型构建、优化算法求解等为一体的集装箱运输组织优化方法,丰富了本领域内的相关研究,研究结论可为未来十年内长江中游区域集装箱船型发展提供一定的参考和借鉴。此外,论文研究有利于支撑多项国家战略的实施,有利于进一步完善我国内河集装箱运输网络和降低社会物流成本,有助于运输企业选定集装箱运输组织优化方案。"
    },
    {
        "name": "宫之光,汪洋,杨忠振.长江经济带出口集装箱运输网络优化设计[J].哈尔滨工程大学学报,2018,39(06):990-997.",
        "abstract": "为最小化运输费用,提出由海运、陆运、水运和换装系统构成的超级网络的数学表达式,然后考虑长江水道不同航道的通航能力、沿线港口的发展以及洋山港的国际物流能力,基于货主的路径选择行为,构建运输组织优化模型,为长江上游的出口集装箱货物指派最优路径。选取长江中下游地区的40个城市作为出口地,东京港、横滨港、名古屋港和神户港作为目的地港,以设置2个干港为前提,分别对设置0、1、2个枢纽河港时的出口集装箱运输进行优化组织,结果表明:设置2个干港以及2个枢纽河港时社会总成本最小。"
    },
    {
        "name": "程超.长江流域集装箱运输方式研究[D].导师：方芳.武汉理工大学,2006.",
        "abstract": "长江是我国第一大河流，流域面积广阔，人口众多，资源丰富，是我国经济发展重心。长江作为“黄金水道”，向外可挟整个流域的经济力量，开拓海外市场；向内可沟通沿海和内地，促进西部资源开发和东部技术的西移。可见，长江流域在发展我国国民经济中有着不可置疑的重要地位和作用。 本文探讨了重庆、武汉、长沙、南京、张家港到上海洋山港集装箱运输方式的优化方案。并将ATB(铰接式推轮和驳船)航线在现有基础上扩展到武汉至洋山、南京至洋山和张家港至洋山方案之中，通过长江流域集装箱运输方式进行论证后，发现ATB船型吃水浅，运量大及其最大的特点——江海直达而不需中转的优点，正好适合大小洋山独特的地理位置，从而能够更好的集聚长江集装箱货源至上海洋山港中转，促进长江流域集装箱运输联动发展。因此，推动长江流域江海联运集装箱运输也是长江“黄金水道”价值的体现，对长江流域集装箱运输方式进行研究，提出长江至洋山最佳运输方式，具有重要的现实意义。 本文在第一章中提出了对长江流域集装箱运输方式研究的背景，阐述了该课题研究目的和意义：第二章，对长江流域集装箱运输系统现状进行定性分析，分别从长江水系自然概况，长江流域主要港口以及运输组织方面展开对现有长江流域集装箱运输系统的分析；本文重点在第三章和第四章部分，在第三章中，分析长江流域集装箱船型选择后，确定方案参数，运用运筹学的方法提出了对长江流域集装箱运输方式进行优化的设想，设立初步方案；第四章主要对方案进行经济技术论证，提出优选结果，并通过运输系统中燃油价格、船舶价格、船舶在港停时和上水载箱量作为参数变量对最优方案进行了敏感性分析；第五章，提出本文的结论，以及未来长江流域集装箱运方式发展的方向。 因此，对长江流域集装箱运输方式进行研究，提出长江至洋山最佳运输方式，具有重要的现实意义，研究结论对政府和企业的有关部门有一定的参考价值。"
    },
    {
        "name": "A Multi-objective Optimization Model of the Intermodal Transportation Network[A].in:American Society of Civil Engineers.International conference on transportation engineering 2009, vol. 2: Second international conference on transportation engineering (ICTE 2009), July 25-27, 2009, Chengdu, China[C].2009.1244-1249.",
        "abstract": "Nowadays the optimization of the intermodal transportation network is an interesting topic on which attracts many people to do research. Consideration the characteristic of the intermodal transportation network, this paper present a multi-objective optimization model under the principle of the minimization of the transportation cost and time. The model quantificationally describes the combined optimization strategy for every transportation modes in the intermodal transportation network. And then the author proposes the solution methods for the multi-objective optimization model based on the Matlab Toolbox. At last, this method is used to settle a simple example which is composed of several cities and four transportation modes. The results indicate that this methodology is effective to find the combined optimization strategy for transporting. And the research enables to help the transportation enterprise (and other organization) select the transportation modes, combined strategy and route."
    },
    {
        "name": "van Duin, R.,van Ham, H.,Institute of Electric and Electronic Engineer.A three-stage modeling approach for the design and organization of intermodal transportation services[A].in:Systems, Man, and Cybernetics, 1998. 1998 IEEE International Conference on vol.4[C].1998.4051-4056.",
        "abstract": "Presents an approach to the modelling of containerized intermodal transport. This approach is strongly connected to the various perspectives of the transportation entrepreneurs and the shippers. The first stage in the approach supports the location choices of potential intermodal terminals. The formalization is based on a linear programming model minimizing the integral transportation costs. 1. Railway or water infrastructure permitting, the model decides on the basis of regional transportation demands whether it is more efficient to service by intermodal transportation or by road transportation. 2. When the rough locations of terminals are identified in a region, a second model is applied to search for the exact location in the region. The preference locations are determined on the basis of their infrastructural unlocking possibilities. A detailed cost model is developed to support this exact location decision. 3. The last part of this approach is focused on the possible customers in the neighborhood of the terminals. Analysis of suitability, timeliness, and deliverance reliability of goods are factors of logistic importance. These aspects of integration both for the terminal and its customers are specified by a simulation model. The approach contains feedback-loops to learn from more detailed insights and has been successfully applied for two new terminal locations."
    },
    {
        "name": "奚静,刘俐,解晓灵.考虑碳排放的多式联运中转枢纽选址[J].物流技术,2023,42(02):74-79.",
        "abstract": "以既有物流园区的货运中转枢纽作为当前多式联运中转枢纽选址的备选地点，综合考虑货运量、货运成本、碳排放等影响因素，利用鲍摩-瓦尔夫模型，以包含货运中转枢纽的运营成本、该批货物在货运中转枢纽前后两段路程的总运输成本、在货运中转枢纽的中转存储成本以及碳排放成本在内的总成本最低为目标，建立多式联运中转枢纽选址模型，求解得出最终选取南京作为最佳的中转枢纽选址地，并对计算结果进行了验证。"
    },
    {
        "name": "丁跃凡,张敏,刘彬彬,吴克非,方亚非,黄泽星,李兵,谢鹏,张和.基于轨道集卡车的江海联运集装箱中转运输系统及方法:湖北省,CN109160296B[P].2020-11-17",
        "abstract": "本发明提供了一种基于轨道集卡车的江海联运集装箱中转运输系统及方法,系统包括：第一港口集装箱管理子系统,用于生成并发送集装箱联运预告信息和装车计划；铁路运输管理子系统,用于启动牵引机车以将停于第一港口预设区域且已装载集装箱的轨道集卡车互相连接,形成已装载集装箱的铁路列车；按照铁路运输计划调度铁路列车行驶至第二港口,发送集装箱联运实际信息；第二港口集装箱管理子系统,用于确定目标堆场位置、目标装卸机和目标运输船并生成卸车计划和装船计划；目标装卸机,用于将部分集装箱装载至目标运输船,将部分集装箱卸载至目标堆场位置。应用本发明实施例,提高了系统通用性和集装箱运输效率。"
    },
    {
        "name": "吕博文,杨斌,朱小林.多式联运情形下货物中转集拼的运作优化[J].计算机应用与软件,2018,35(11):122-129.",
        "abstract": "基于需求订单的个性化和多样化,从物流组织的角度建立模型。考虑决策有关的小批量多起点和目的地货物的装卸、整合、转运等因素,通过集装箱作业节点和运输路线的选择,边装边卸,充分利用集装箱。同时设计遗传算法,采用双层染色体编码方式,交叉映射操作、变异和逆转操作,保障解的全局最优性。得出总成本、所需集装箱个数与弹性系数的反比关系,并且可提高15. 86%的吨位利用率,证明方法和模型的可行性和科学性。"
    },
    {
        "name": "毛晓颖.基于低碳视角的上海港集装箱多式联运中转站布局优化研究[D].导师：姜宝.中国海洋大学,2013.",
        "abstract": "本文内容如下：首先，对多式联运网络构成进行了详细分析，并对集装箱多式联运中转站的概念、功能及其分类进行了归纳总结。在此基础上对我国多式联运网络的现状进行了总结，并分析了多式联运网络及中转站布局存在的问题。其次，在归纳总结低碳经济与碳减排内涵的基础上，分析了低碳经济对交通运输业产生的影响。根据《2006年IPCC国家温室气体清单指南》中提供的方法，结合相关资料比较分析了公路运输、铁路运输以及内河水运的单位能耗和碳排放量。第三，对上海港合理布局腹地范围内集装箱多式联运中转站的必要性进行了分析，对上海港内部环境和腹地经济、交通环境的现状进行了分析，并详细分析了上海港集装箱运输网络各种运输方式通道现状，在此基础上进一步分析了合理布局中转站的必要性。最后，采用模糊C-均值聚类分析对上海港腹地范围内的集装箱中转站进行布局优化，并对中转站的规模及辐射范围进行划分。在此基础上对上海港集装箱海铁联运和河海联运的能耗、碳排量及碳税效益进行比较分析。"
    },
    {
        "name": "施俊,施芸.一种便于取放的基于多式联运智能运输平台:江苏省,CN217919942U[P].2022-11-29",
        "abstract": "本实用新型公开了一种便于取放的基于多式联运智能运输平台,包括：起始平台,所述起始平台端部固定连接中转平台,所述中转平台内部设有转向区,所述转向区外侧固定连接分流平台,所述起始平台包括支撑台,所述支撑台右端顶部固定安装活动块,所述活动块左右对称设有两组,两组所述活动块配合转动连接第一侧板,所述支撑台设置为z形,本实用新型通过设置起始平台,在第一传送辊表面均匀固定安装重力感应器,从而方便通过重力感应器感应到起始平台顶部是否有放置了需要输送,从而方便通过重力感应器联动控制起始平台、中转平台进行工作,从而方便提高传动带传送时的节能型,提高了设备使用的经济性。"
    },
    {
        "name": "龚丽萍.基于轴辐式网络的危险品水陆联运中转点选址及收费策略研究[D].导师：张冠湘;许伟琦.华南理工大学,2021.",
        "abstract": "我国危险品的运输量逐年上升,而运输过程中事故屡有发生,又由于轴辐式的网络能够有效的减少运输企业的成本,已经成为部分运输企业远距离运输的优选,根据这一运输趋势,本文针对基于轴辐式网络的危险品水陆联运网络进行研究。另有研究表明,中转点的选址规划对网络效用有正向影响、收费的调控方法能够引导企业选择低风险的港口,弥补禁行策略在解集较少、有时无法达到网络风险最小的缺点。故,本文主要从政府的角度出发,以风险最小化为目标,构建危险品水陆联运模式中转点的选址及收费模型,实现港口不同种类危险品转运资质的颁发、转运容量的规定和收费策略的制定。主要的研究内容为:(1)港口风险评价模型的构建。利用层次分析法和专家法,构建港口作业的风险评价模型,并根据国家监管部门规定的ALARP准则,构建港口的风险容量模型。(2)基于禁行策略的港口选址模型的构建。基于双层规划和轴幅式网络构建危险品水陆联运中转点的选址模型。(3)结合收费策略的选址模型构建。主要为结合两种收费策略建立的选址收费模型,分别为基于成本对部分港口收取额外费用的固定收费策略,和基于风险并结合ALARP准则分段收费的灵活收费策略。最终,利用珠三角地区的危险品运输需求和路网,对本文模型进行分析。得到结论:(1)人员操作因素在各风险影响因素中权重较高,应加强港口的人员培训工作。(2)三种选址策略均对网络总风险和政府管理成本有减少的作用。但优势各异,灵活收费策略对风险的调控作用最佳,固定收费策略能够有效的增大最终港口的解集,企业可选择余地更强,禁行策略对政府管理能力要求最低。(3)相比两种收费方式,灵活收费策略优势为风险调控作用,固定收费策略优势喂收费方式简单易执行,企业接受程度更高;(4)港口数量与网络总风险并非为线性负相关,政府应根据管理能力及管理成本的考量,选择选址策略及开放的港口的数量。(5)三种选址策略下,部分港口的潜在风险均较大,应重点关注流量较高的港口。"
    },
    {
        "name": "申勇.国际集装箱海铁联运中转效率优化方法研究[D].导师：帅斌.西南交通大学,2019.",
        "abstract": "国家实行对外开放以来与全球化经济接轨、不断加快国际贸易的发展进程,给国际集装箱海铁联运带来了新的发展机遇,我国沿海港口的海铁联运态势虽然在逐年上升,但海铁联运总量占港口吞吐量的平均比例较低,与国外港口差距较大。造成该种情况的原因之一是海铁联运的效率与公路运输相比相对较低。所以,提升国际集装箱海铁联运运输效率是非常重要的,而集装箱在港站与港口之间的中转是集装箱海铁联运运输过程的关键环节。国际集装箱海铁联运中转效率问题的研究,能促进国际集装箱海铁联运更好地发展,帮助实现其强大的运输能力。论文主要研究以下几个内容:首先通过对我国集装箱海铁联运的现状进行分析,对部分港口的海铁联运运量进行预测,分析得到海铁联运中存在的问题,其中集装箱的拆装箱问题对中转效率具有较大影响。然后通过将集装箱中转流程分为进口拆装箱流程,进口不拆装箱流程,出口拆装箱流程以及出口不拆装箱流程,分析了海铁联运集装箱在港站与港口之间的中转流程。结合海铁联运发展现状的分析,提出了在港站为海铁联运集装箱专门设置拆装箱场以代替码头货运站来进行海铁联运集装箱的拆箱和装箱作业;给出了单独设置拆装箱场的原因,并对设置拆装箱场后的集装箱中转流程进行了分析。接着在设置拆装箱场的基础上,构建了港站内出口集装箱在装卸线、拆装箱场以及港湾站集装箱堆场之间的转运优化模型,并提出使用VC++对转运过程进行仿真的方式求解。最后设计算例,以国际集装箱海铁联运中转效率优化模型对算例数据进行仿真,对仿真结果进行对比分析,给出了算例中港站的装卸运输机械合理配备方案,以实现港站内部的最小资源效率最大化,从而提高集装箱在港站与港口之间的中转效率。"
    },
    {
        "name": "Karim, Mohammad Anwarul..Development of a systems approach to planning, design and operations of intermodal passenger transfer facilities to increase the mobility and safety of older travelers.[D].West Virginia University.,1998.",
        "abstract": "America, as a society, is aging. Currently, 13% of the population is 65 years of age or older. This percentage is expected to rise to 21% by 2030. Since older travelers frequently suffer from one or more age-related physical and/or information handling decrements, they often have problems using intermodal passenger transfer facilities.; The overall goal of this study was to develop a framework which can provide an approach to identify older traveler issues associated with intermodal passenger transfer facilities and serve to guide planning and engineering improvements to intermodal passenger transfer facilities to increase the safety and mobility of older travelers. This objective was achieved by developing an older traveler plan (OTP) for intermodal passenger transfer facilities as a tool for transportation practitioners in real application on the basis of analyses of the results of an older traveler survey, information on a unique systems approach to older transportation in Waterloo, Iowa, and information from existing literature on older travel.; Overall results of this study tended to confirm the hypothesis that a systems approach to planning, designing and operating an intermodal passenger transfer facility is appropriate to address the problems of older travelers. The older traveler plan (OTP) which includes a step-by-step approach, is a simple, effective tool which is expected to help support transportation planners and traffic engineers in planning, designing, implementing, operating, and maintaining intermodal passenger transfer facilities to increase the mobility and safety of older travelers. This was confirmed by a limited survey of transportation practitioner."
    },
    {
        "name": "刘涛,雷正玲,高进.一种基于空间数据融合的水上交通事故航迹模拟方法:上海市,CN112150616A[P].2020-12-29",
        "abstract": "本发明公开了一种基于空间数据融合的水上交通事故航迹模拟方法,属于数据模拟技术领域。针对国内外还没有成熟的水上交通事故再现模拟分析方法,本发明通过多源空间数据融合的水上交通事故场景,为事故分析与判定提供综合的空间信息服务,在多源空间数据融合和AIS等船舶航行数据的基础上,研究了水上交通事故再现模拟中的航迹模拟,设计了基于多源空间数据融合的水上交通事故航迹模拟方案,给出了航迹模拟实现的方法,开发了基于多源空间数据融合的水上交通事故航迹模拟系统,并应用到船舶碰撞这一典型水上交通事故,为水上交通事故再现模拟研究提供了新的应用模式。"
    },
    {
        "name": "车飞.基于Access的船舶交通数据库在船舶交通仿真的应用[J].舰船科学技术,2020,42(20):43-45.",
        "abstract": "由于船舶的数量不断增加,港口、航道内的船舶碰撞等交通事故频发。为了提高船舶航行的安全性,提高海上交通管理的水平,业内的研究人员针对船舶交通仿真系统做了大量的研究。由于船舶交通仿真过程需要采集大量的船舶航行数据,因此,提高交通仿真系统的数据库性能显得非常重要。Access数据库技术是一种非常成熟的数据开发和管理技术,本文结合Access数据库技术设计了船舶的交通仿真系统,重点介绍了仿真系统的数据类型及Access接口设计。"
    },
    {
        "name": "熊峻霆.海上交通流模拟中避碰模型的研究[D].导师：谢洪彬.大连海事大学,2019.",
        "abstract": "随着航运事业的飞速发展和造船技术的进步,伴随而来的是海上交通日趋繁忙和船舶操作更为复杂,这大大增加了海上交通事故风险。海上交通流模拟作为研究海上交通问题的重要技术手段,对海上交通规划和海上交通流评价等问题的解决具有指导意义。避碰模型是海上交通流模拟研究的核心之一,传统的交通流模拟技术存在模拟的逼真度不高或时效性较差等问题,需要引入新的方法对模型进行改进。论文在分析已有海上交通流模拟的建模精度和实用性不足的基础上,提出一种基于强化学习的船舶避碰模型,主要研究包括以下几方面:(1)收集真实海域的船舶AIS数据,对数据进行解码、预处理工作,利用ArcGIS在地图上再现海上交通流,使用Hadoop技术筛选出现过会遇局面的航行轨迹数据,在众多会遇局面中选择三种比较典型的会遇局面。(2)选择强化学习中的深度Q学习算法进行避碰模型的建模。通过航海模拟器对三种会遇局面在相同经纬度、相同航行状态和相同风流影响下进行实操模拟,截取实操模拟图作为仿真结果的对比参照物。(3)进行避碰模型的训练,将航行轨迹数据通过卷积神经网络对Q学习模型进行训练,当网络目标Q值与真实Q值间的误差满足预设精度或达到最大训练次数时停止训练,输出模型完成对避碰策略的学习。(4)设计仿真实验,将三种会遇局面的船舶初始状态数据输入避碰模型中,用Matlab工具对结果进行仿真,对比仿真结果图与实操模拟图。再将避碰模型模拟效果与传统海上交通流模拟效果进行对比,分析模拟逼真度和时效性。"
    },
    {
        "name": "张新宇,姚舜,陈向,姜玲玲,林彬,荣凯,陈华,许长彬,何鑫,朱绍凡.一种基于样本分析的船舶交通流模拟生成方法:辽宁省,CN106156428B[P].2019-05-10",
        "abstract": "本发明公开了一种基于样本分析的船舶交通流模拟生成方法,其特征在于,包括如下步骤：初始化仿真系统内的船舶交通流永久实体并建立对应的航道网络模型；根据港口历史交通流数据,基于样本分析的随机数生成算法初始化仿真系统内的船舶交通流船舶实体并配置每一船舶交通流船舶实体所对应的初始化属性；创建船舶交通流永久实体与船舶交通流船舶实体的仿真关系,并以每一船舶交通流船舶实体驶入下一段航道或锚地或泊位为船舶事件,确定仿真过程中每一次推进步长,以生成船舶安排进出港仿真进程。本发明能够实现任意港口、任意时间跨度的船舶交通流模拟生成过程,其通过计算机自动模拟出更符合真实交通流规律的仿真交通流,对应的通用性更强。"
    },
    {
        "name": "赵鹏.基于电子海图的船舶交通流模拟研究[D].导师：张吉平.大连海事大学,2015.",
        "abstract": "水路运输是交通运输系统的重要组成部分,随着经济的快速发展以及国际贸易的不断扩大,其在综合运输体系中的地位和作用日益凸显。国际货物运输的快速性、高效性要求使得船舶大型化、高速化成为不可阻挡的发展趋势,由此带来一系列问题：港口船舶交通量不断增大,船舶交通流的构成不断多样化,行为特征不断复杂化,船舶通航安全、通航效率和通航资源之间的矛盾日益突出。这些问题给经济带来巨大的损失的同时,逐渐成为限制运输事业发展的因素。港口是一个结构复杂、功能全面的随机服务系统,港口规模及服务效率直接影响着港口的服务水平。由于船舶到港、泊位服务时间的随机性以及港口服务的复杂性,港口船舶排队问题很难通过解析找到解决方法。采用系统模拟的方法对港口船舶交通流模拟,合理优化港口泊位锚地规模及船舶交通组织成为目前应用广泛的解决手段。本文在交通流统计的基础上,从系统的角度出发,对系统构成要素以及规则进行分析,运用排队论方法,建立M/M/N港口船舶交通流排队模型。船舶交通流模拟系统采用面向对象的程序设计思想,运用通用程序设计语言Visual C++作为编译语言,在电子海图平台上实现了对船舶在港口所有活动以及港口服务规律的可视化模拟。船舶交通流模拟系统对模拟中船舶及锚地的活动过程进行了详细记录,通过分析系统模拟中船舶交通流的行为特征以及港口泊位、锚地服务系统的服务水平,得出造成港口船舶排队等待的原因并由此对港口规模以及船舶交通组织的优化提出改进意见。"
    },
    {
        "name": "吴春杰.基于船舶交通模拟实验的水域通航风险评估[J].船海工程,2011,40(02):156-160.",
        "abstract": "基于水域通航环境的分析和船舶流量的统计,采用VB 6.0编程方法设计并建立船舶交通模拟实验平台,对船舶会遇信息进行统计分析,从而实现通航风险的有效评估,其评价结果具有实时性和区域性分布的特点。"
    },
    {
        "name": "Yanyi Chen,Hongyu Wu,Zhe Wen.Study on the Propagation and Dissipation of Inland Ship Congestion under Different Control Strategies[A].in:AIP Publishing,.Materials science, engergy technology, and power engineering I : Part B /[C].2017.020139-1-020139-8.",
        "abstract": "Inland waterway transportation is an important part of the comprehensive transportation system of sustainable development, and it is also a way of transportation which is restricted by natural conditions greatly. In recent years, the problems of insufficient traffic capacity of The Three Gorges become prominent due to lhe increasing in the number of ships. And the ship ' s detention caused by gale, frog, accident and one-way traffic in dry season has occurred, which not only increased the pressure of the navigable waterway but also seriously affected the safety of shipping. Based on the different types of ships, the Arena software was used to simulate the ship traffic flow. The paper analyzed the traffic congestion propagation and dissipation rule of the ship under different navigation control methods, and provided decision reference for the navigation management department to formulate the relevant navigation control strategy"
    },
    {
        "name": "LIU Jingxian,ZHOU Feng,WANG Maoqing.Simulation of waterway traffic flow at harbor based on the ship behavior and cellular automata[A].in:[s.n.].Asia navigation conference 2010, KINPR-CIN-JIN joint symposium 2010[C].2010.305-311.",
        "abstract": "Simulation of waterway traffic flow at harbor can effectively verify the rationality of the harbor waterway traffic flow's statistics and prediction, reveal the basic law of the development of traffic flow. In this paper, the cellular automata model of waterway traffic flow at harbor was developed on basis of different classes of vessels, safe distance, ship arriving law and berths' service level. The proposed model solves the problems of complexity and non-linearity effectively in the simulation of waterway traffic flow at harbor, and the results show that this model conforms better to the actual conditions, which has an important theoretical value and practical significance to the port traffic control and management."
    }]